server:
  port: 8091

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/operations}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
